spring:
  application:
    name: ratelimiter
  redis:
    lettuce:
      pool:
        max-active: 8
        max-idle: 8
        max-wait: -1
    url: redis://127.0.0.1:6379
    database: 0
server:
  port: 8080

